print("เขียนแสดงรายชื่อนักเรียนในห้องทั้งหมดค่ะ")
names = [
    "julaluck kongjaroon 1",
    "Traikoon Boonnam 2",
    "Woranasak Kaitphichetchuen 3",
    "Nontawat Khamduang 4",
    "Panupong Saison 5",
    "punnagron  phungsuwan 6",
    "Wissarut Klinrueang 7",
    "Amornthep Unno 8",
    "Jakkrich testong 9",
    "Jiratha Noisree 10",
    "Kornpipat Leknak 11",
    "Phattharaphon  Chomput 12",
    "Supachai Rungsang 13",
    "Nattapon Pluemkitmongkol 14",
    "Pharat Dananansuk 15",
    "Ruangwit Chokchai 16",
    "Jirayut Buranachan 17", 
    "Natcha Kumpa 18",
    "Savitri  Minsaman 19",
    "Bannaporn Siriphan 20",
    "Yanisa  Phaungpee 21",
    "Kityada Jitwimonrat 22",
    "Sudarat Suanyim 23",
    "Ploypraphat Pissaruk 24",
    "Thatchanok Samai 25",
    "Pearpilai  Boonkrong 26",
    "Kanyaphorn  Sittiwong 27",
    "Kankao Sittho 28 ",
    "Kittima Kreidarporn 29",
    "Apitsada Wachirasreesoontra 30",
    "Sirikarn Baotun 31",
    "Kanyawee  Udomsaree 32",
    "Nattarinee Chimreaung 33",
    "Pichporn Meechoksom 34",
    "Kannisa Ratrueangudom 35",
    "Chuda Sariphan 36",
    "Kanta Piyapattharakul 37",
    "Napaspornprom Tancharakorn 38",
    "Kingkan Roumpol 39",
    "Wachiraya Wachiranawin 40",
]
for name in names :
    if name != "Kanyaphorn Sittiwong 27":
        print(name)
        print('--end--')
